### ISSUE TITLE
Not updating the JWT_SECRET

### ISSUE THREAD

**Issue by itsazzad** [petervmeijgaard/jwt-example#1]
``` 
php artisan jwt:generate 
``` 
Not updating the JWT_SECRET in .env

**Comment by petervmeijgaard** [comment]
That's an issue of the JWT package. This is out of the scope of this project.
[This](https://github.com/tymondesigns/jwt-auth) is the used package for the JWT-authentication

**Comment by petervmeijgaard** [comment]
I fixed it by copying the token in the output of `php artisan jwt:generate` and pasting it in the `.env`-file

**Comment by itsazzad** [comment]
I also did the same...
